image: node:8-jessie

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | base64 -d | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan si-nexus01.dev.setl.io >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - npm install --only=dev

test:
  script:
      - npm test
