language: node_js

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

node_js:
  - '7'
  - '6'
before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g yarn

install:
  - yarn

before_script:
  - npm prune

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - npm run test