#!/bin/sh

YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo "${YELLOW}Stopping other instances of setl/frontend...${NC}"
docker stop setl-frontend
docker rm setl-frontend

echo "${YELLOW}Installing Frontend...${NC}"
npm install
docker build --no-cache -t setl/frontend .

echo "${YELLOW}Launching Frontend...${NC}"
docker run --name setl-frontend -p 4202:4200 --link setl-backend -d setl/frontend:latest

echo "${GREEN}Complete. You can access the frontend via localhost:4200.${NC}"

echo "${GREEN}╔═╗╔═╗╔╦╗╦  
╚═╗║╣  ║ ║  
╚═╝╚═╝ ╩ ╩═╝/frontend${NC}"