#!/bin/bash

yarn link @setl/asset-servicing
yarn link @setl/core-account
yarn link @setl/core-balances
yarn link @setl/core-connections
yarn link @setl/core-corp-actions
yarn link @setl/core-filedrop
yarn link @setl/core-fileviewer
yarn link @setl/core-layout
yarn link @setl/core-login
yarn link @setl/core-manage-member
yarn link @setl/core-messages
yarn link @setl/core-persist
yarn link @setl/core-req-services
yarn link @setl/core-store
yarn link @setl/core-t2s
yarn link @setl/core-useradmin
yarn link @setl/core-wfe
yarn link @setl/multilingual
yarn link @setl/permission-grid
yarn link @setl/utils
yarn link @setl/websocket-service
yarn link @ofi/ofi-main
yarn link @ofi/product
