const unitTrustItems = [ // Unit Trust / Unit Investment Trust (UIT)
    { id: '0', text: 'GB Authorised unit trust (AUT)' },
    { id: '1', text: 'US For US UIT refer to "US Mutual Fund"' },
    { id: '2', text: 'KY (Exempted) Unit trust' },
    { id: '3', text: 'IE Unit trust' },
    { id: '4', text: 'VG Unit trust' },
    { id: '5', text: 'VM Unit trust' },
    { id: '6', text: 'GG Unit trust' },
    { id: '7', text: 'JE Unit trust' },
    { id: '8', text: 'HK Unit trust' },
    { id: '9', text: 'SG Unit trust' },
    { id: '10', text: 'MT Unit trust' },
];

export enum typeOfEuDirective {
    UCITS = 1,
    AIF,
    Other,
}


export enum isFundStructure {
    FUND,
    UMBRELLA,
}

export enum isEuDirective {
    NO,
    YES,
}

export enum openOrCloseEnded {
    CLOSE_ENDED,
    OPEN_ENDED,
}

export enum isFundOfFund {
    NO,
    YES,
}

export enum isDedicatedFund {
    NO,
    YES,
}

export enum hasEmbeddedDirective {
    NO,
    YES,
}

export enum hasCapitalPreservation {
    NO,
    YES,
}

export enum hasCppi {
    NO,
    YES,
}

export enum hasHedgeFundStrategy {
    NO,
    YES,
}

export enum isLeveraged {
    NO,
    YES,
}

export enum has130_30Strategy {
    NO,
    YES,
}

export enum isFundTargetingEos {
    NO,
    YES,
}

export enum isFundTargetingSri {
    NO,
    YES,
}

export enum isPassiveFund {
    NO,
    YES,
}

export enum hasSecurityiesLending {
    NO,
    YES,
}

export enum hasSwap {
    NO,
    YES,
}

export enum hasDurationHedge {
    NO,
    YES,
}

export const enums = {
    typeOfEuDirective,
    isFundStructure,
    isEuDirective,
    openOrCloseEnded,
    isFundOfFund,
    isDedicatedFund,
    hasEmbeddedDirective,
    hasCapitalPreservation,
    hasCppi,
    hasHedgeFundStrategy,
    isLeveraged,
    has130_30Strategy,
    isFundTargetingEos,
    isFundTargetingSri,
    isPassiveFund,
    hasSecurityiesLending,
    hasSwap,
    hasDurationHedge,
};


export const fundItems = {
    domicileItems: [
        {id: 'AF', text: 'Afghanistan'},
        {id: 'AL', text: 'Albania'},
        {id: 'DZ', text: 'Algeria'},
        {id: 'AS', text: 'American Samoa'},
        {id: 'AD', text: 'Andorra'},
        {id: 'AO', text: 'Angola'},
        {id: 'AI', text: 'Anguilla'},
        {id: 'AQ', text: 'Antarctica'},
        {id: 'AG', text: 'Antigua And Barbuda'},
        {id: 'AR', text: 'Argentina'},
        {id: 'AM', text: 'Armenia'},
        {id: 'AW', text: 'Aruba'},
        {id: 'AU', text: 'Australia'},
        {id: 'AT', text: 'Austria'},
        {id: 'AZ', text: 'Azerbaijan'},
        {id: 'BS', text: 'Bahamas'},
        {id: 'BH', text: 'Bahrain'},
        {id: 'BD', text: 'Bangladesh'},
        {id: 'BB', text: 'Barbados'},
        {id: 'BY', text: 'Belarus'},
        {id: 'BE', text: 'Belgium'},
        {id: 'BZ', text: 'Belize'},
        {id: 'BJ', text: 'Benin'},
        {id: 'BM', text: 'Bermuda'},
        {id: 'BT', text: 'Bhutan'},
        {id: 'BO', text: 'Bolivia'},
        {id: 'BA', text: 'Bosnia And Herzegovina'},
        {id: 'BW', text: 'Botswana'},
        {id: 'BV', text: 'Bouvet Island'},
        {id: 'BR', text: 'Brazil'},
        {id: 'IO', text: 'British Indian Ocean Territory'},
        {id: 'BN', text: 'Brunei Darussalam'},
        {id: 'BG', text: 'Bulgaria'},
        {id: 'BF', text: 'Burkina Faso'},
        {id: 'BI', text: 'Burundi'},
        {id: 'KH', text: 'Cambodia'},
        {id: 'CM', text: 'Cameroon'},
        {id: 'CA', text: 'Canada'},
        {id: 'CV', text: 'Cape Verde'},
        {id: 'KY', text: 'Cayman Islands'},
        {id: 'CF', text: 'Central African Republic'},
        {id: 'TD', text: 'Chad'},
        {id: 'CL', text: 'Chile'},
        {id: 'CN', text: 'China'},
        {id: 'CX', text: 'Christmas Island'},
        {id: 'CC', text: 'Cocos (keeling) Islands'},
        {id: 'CO', text: 'Colombia'},
        {id: 'KM', text: 'Comoros'},
        {id: 'CG', text: 'Congo'},
        {id: 'CD', text: 'Congo, The Democratic Republic Of The'},
        {id: 'CK', text: 'Cook Islands'},
        {id: 'CR', text: 'Costa Rica'},
        {id: 'CI', text: 'Cote D\'ivoire'},
        {id: 'HR', text: 'Croatia'},
        {id: 'CU', text: 'Cuba'},
        {id: 'CY', text: 'Cyprus'},
        {id: 'CZ', text: 'Czech Republic'},
        {id: 'DK', text: 'Denmark'},
        {id: 'DJ', text: 'Djibouti'},
        {id: 'DM', text: 'Dominica'},
        {id: 'DO', text: 'Dominican Republic'},
        {id: 'TP', text: 'East Timor'},
        {id: 'EC', text: 'Ecuador'},
        {id: 'EG', text: 'Egypt'},
        {id: 'SV', text: 'El Salvador'},
        {id: 'GQ', text: 'Equatorial Guinea'},
        {id: 'ER', text: 'Eritrea'},
        {id: 'EE', text: 'Estonia'},
        {id: 'ET', text: 'Ethiopia'},
        {id: 'FK', text: 'Falkland Islands (malvinas)'},
        {id: 'FO', text: 'Faroe Islands'},
        {id: 'FJ', text: 'Fiji'},
        {id: 'FI', text: 'Finland'},
        {id: 'FR', text: 'France'},
        {id: 'GF', text: 'French Guiana'},
        {id: 'PF', text: 'French Polynesia'},
        {id: 'TF', text: 'French Southern Territories'},
        {id: 'GA', text: 'Gabon'},
        {id: 'GM', text: 'Gambia'},
        {id: 'GE', text: 'Georgia'},
        {id: 'DE', text: 'Germany'},
        {id: 'GH', text: 'Ghana'},
        {id: 'GI', text: 'Gibraltar'},
        {id: 'GR', text: 'Greece'},
        {id: 'GL', text: 'Greenland'},
        {id: 'GD', text: 'Grenada'},
        {id: 'GP', text: 'Guadeloupe'},
        {id: 'GU', text: 'Guam'},
        {id: 'GT', text: 'Guatemala'},
        {id: 'GN', text: 'Guinea'},
        {id: 'GW', text: 'Guinea-bissau'},
        {id: 'GY', text: 'Guyana'},
        {id: 'HT', text: 'Haiti'},
        {id: 'HM', text: 'Heard Island And Mcdonald Islands'},
        {id: 'VA', text: 'Holy See (vatican City State)'},
        {id: 'HN', text: 'Honduras'},
        {id: 'HK', text: 'Hong Kong'},
        {id: 'HU', text: 'Hungary'},
        {id: 'IS', text: 'Iceland'},
        {id: 'IN', text: 'India'},
        {id: 'ID', text: 'Indonesia'},
        {id: 'IR', text: 'Iran, Islamic Republic Of'},
        {id: 'IQ', text: 'Iraq'},
        {id: 'IE', text: 'Ireland'},
        {id: 'IL', text: 'Israel'},
        {id: 'IT', text: 'Italy'},
        {id: 'JM', text: 'Jamaica'},
        {id: 'JP', text: 'Japan'},
        {id: 'JO', text: 'Jordan'},
        {id: 'KZ', text: 'Kazakstan'},
        {id: 'KE', text: 'Kenya'},
        {id: 'KI', text: 'Kiribati'},
        {id: 'KP', text: 'Korea, Democratic People\'s Republic Of'},
        {id: 'KR', text: 'Korea, Republic Of'},
        {id: 'KV', text: 'Kosovo'},
        {id: 'KW', text: 'Kuwait'},
        {id: 'KG', text: 'Kyrgyzstan'},
        {id: 'LA', text: 'Lao People\'s Democratic Republic'},
        {id: 'LV', text: 'Latvia'},
        {id: 'LB', text: 'Lebanon'},
        {id: 'LS', text: 'Lesotho'},
        {id: 'LR', text: 'Liberia'},
        {id: 'LY', text: 'Libyan Arab Jamahiriya'},
        {id: 'LI', text: 'Liechtenstein'},
        {id: 'LT', text: 'Lithuania'},
        {id: 'LU', text: 'Luxembourg'},
        {id: 'MO', text: 'Macau'},
        {id: 'MK', text: 'Macedonia, The Former Yugoslav Republic Of'},
        {id: 'MG', text: 'Madagascar'},
        {id: 'MW', text: 'Malawi'},
        {id: 'MY', text: 'Malaysia'},
        {id: 'MV', text: 'Maldives'},
        {id: 'ML', text: 'Mali'},
        {id: 'MT', text: 'Malta'},
        {id: 'MH', text: 'Marshall Islands'},
        {id: 'MQ', text: 'Martinique'},
        {id: 'MR', text: 'Mauritania'},
        {id: 'MU', text: 'Mauritius'},
        {id: 'YT', text: 'Mayotte'},
        {id: 'MX', text: 'Mexico'},
        {id: 'FM', text: 'Micronesia, Federated States Of'},
        {id: 'MD', text: 'Moldova, Republic Of'},
        {id: 'MC', text: 'Monaco'},
        {id: 'MN', text: 'Mongolia'},
        {id: 'MS', text: 'Montserrat'},
        {id: 'ME', text: 'Montenegro'},
        {id: 'MA', text: 'Morocco'},
        {id: 'MZ', text: 'Mozambique'},
        {id: 'MM', text: 'Myanmar'},
        {id: 'NA', text: 'Namibia'},
        {id: 'NR', text: 'Nauru'},
        {id: 'NP', text: 'Nepal'},
        {id: 'NL', text: 'Netherlands'},
        {id: 'AN', text: 'Netherlands Antilles'},
        {id: 'NC', text: 'New Caledonia'},
        {id: 'NZ', text: 'New Zealand'},
        {id: 'NI', text: 'Nicaragua'},
        {id: 'NE', text: 'Niger'},
        {id: 'NG', text: 'Nigeria'},
        {id: 'NU', text: 'Niue'},
        {id: 'NF', text: 'Norfolk Island'},
        {id: 'MP', text: 'Northern Mariana Islands'},
        {id: 'NO', text: 'Norway'},
        {id: 'OM', text: 'Oman'},
        {id: 'PK', text: 'Pakistan'},
        {id: 'PW', text: 'Palau'},
        {id: 'PS', text: 'Palestinian Territory, Occupied'},
        {id: 'PA', text: 'Panama'},
        {id: 'PG', text: 'Papua New Guinea'},
        {id: 'PY', text: 'Paraguay'},
        {id: 'PE', text: 'Peru'},
        {id: 'PH', text: 'Philippines'},
        {id: 'PN', text: 'Pitcairn'},
        {id: 'PL', text: 'Poland'},
        {id: 'PT', text: 'Portugal'},
        {id: 'PR', text: 'Puerto Rico'},
        {id: 'QA', text: 'Qatar'},
        {id: 'RE', text: 'Reunion'},
        {id: 'RO', text: 'Romania'},
        {id: 'RU', text: 'Russian Federation'},
        {id: 'RW', text: 'Rwanda'},
        {id: 'SH', text: 'Saint Helena'},
        {id: 'KN', text: 'Saint Kitts And Nevis'},
        {id: 'LC', text: 'Saint Lucia'},
        {id: 'PM', text: 'Saint Pierre And Miquelon'},
        {id: 'VC', text: 'Saint Vincent And The Grenadines'},
        {id: 'WS', text: 'Samoa'},
        {id: 'SM', text: 'San Marino'},
        {id: 'ST', text: 'Sao Tome And Principe'},
        {id: 'SA', text: 'Saudi Arabia'},
        {id: 'SN', text: 'Senegal'},
        {id: 'RS', text: 'Serbia'},
        {id: 'SC', text: 'Seychelles'},
        {id: 'SL', text: 'Sierra Leone'},
        {id: 'SG', text: 'Singapore'},
        {id: 'SK', text: 'Slovakia'},
        {id: 'SI', text: 'Slovenia'},
        {id: 'SB', text: 'Solomon Islands'},
        {id: 'SO', text: 'Somalia'},
        {id: 'ZA', text: 'South Africa'},
        {id: 'GS', text: 'South Georgia And The South Sandwich Islands'},
        {id: 'ES', text: 'Spain'},
        {id: 'LK', text: 'Sri Lanka'},
        {id: 'SD', text: 'Sudan'},
        {id: 'SR', text: 'Suriname'},
        {id: 'SJ', text: 'Svalbard And Jan Mayen'},
        {id: 'SZ', text: 'Swaziland'},
        {id: 'SE', text: 'Sweden'},
        {id: 'CH', text: 'Switzerland'},
        {id: 'SY', text: 'Syrian Arab Republic'},
        {id: 'TW', text: 'Taiwan, Province Of China'},
        {id: 'TJ', text: 'Tajikistan'},
        {id: 'TZ', text: 'Tanzania, United Republic Of'},
        {id: 'TH', text: 'Thailand'},
        {id: 'TG', text: 'Togo'},
        {id: 'TK', text: 'Tokelau'},
        {id: 'TO', text: 'Tonga'},
        {id: 'TT', text: 'Trinidad And Tobago'},
        {id: 'TN', text: 'Tunisia'},
        {id: 'TR', text: 'Turkey'},
        {id: 'TM', text: 'Turkmenistan'},
        {id: 'TC', text: 'Turks And Caicos Islands'},
        {id: 'TV', text: 'Tuvalu'},
        {id: 'UG', text: 'Uganda'},
        {id: 'UA', text: 'Ukraine'},
        {id: 'AE', text: 'United Arab Emirates'},
        {id: 'GB', text: 'United Kingdom'},
        {id: 'US', text: 'United States'},
        {id: 'UM', text: 'United States Minor Outlying Islands'},
        {id: 'UY', text: 'Uruguay'},
        {id: 'UZ', text: 'Uzbekistan'},
        {id: 'VU', text: 'Vanuatu'},
        {id: 'VE', text: 'Venezuela'},
        {id: 'VN', text: 'Viet Nam'},
        {id: 'VG', text: 'Virgin Islands, British'},
        {id: 'VI', text: 'Virgin Islands, U.s.'},
        {id: 'WF', text: 'Wallis And Futuna'},
        {id: 'EH', text: 'Western Sahara'},
        {id: 'YE', text: 'Yemen'},
        {id: 'ZM', text: 'Zambia'},
        {id: 'ZW', text: 'Zimbabwe'},
    ],
    umbrellaItems: [
        {
            id: '0',
            text: 'none'
        },
    ],
    typeOfEuDirectiveItems: [
        {
            id: typeOfEuDirective.UCITS,
            text: 'UCITS',
        },
        {
            id: typeOfEuDirective.AIF,
            text: 'AIF',
        },
        {
            id: typeOfEuDirective.Other,
            text: 'Other',
        },
    ],
    UCITSVersionItems: [
        {
            id: 3,
            text: 'UCITS III',
        },
        {
            id: 4,
            text: 'UCITS IV',
        },
        {
            id: 5,
            text: 'UCITS V',
        },
        {
            id: 6,
            text: 'UCITS VI',
        },
    ],
    fundLegalFormItems: [
        { id: '0', text: 'Contractual Fund', },
        { id: '1', text: 'Company With Variable Capital (SICAV)', },
        { id: '2', text: 'Open-ended Investment Company (OEIC)', },
        { id: '3', text: 'Company With Fixed Capital (SICAF)', },
        { id: '4', text: 'Unit Trust', },
        { id: '5', text: 'Unit Investment Trust (UIT)', },
        { id: '6', text: 'Limited Partnership (LP)', },
        { id: '7', text: 'Limited Liability Partnership (LLP)', },
        { id: '8', text: 'Exempted Limited Partnership (ELP)', },
        { id: '9', text: 'Company treated as Limited Partnership', },
        { id: '10', text: 'Limited Company', },
        { id: '11', text: 'Limited Liability Company (LLC)', },
        { id: '12', text: 'Exempted Limited Liability Company', },
        { id: '13', text: 'Exempted Company', },
        { id: '14', text: 'Corporation', },
        { id: '15', text: 'International Business Company (IBC)', },
        { id: '16', text: 'Cell Company (ICC / PCC)', },
        { id: '17', text: 'Trust', },
        { id: '18', text: 'US Mutual Fund', },
        { id: '19', text: 'US Face Amount Certificate Company (FAC)', },
        { id: '20', text: 'US engaged Partnership', },
        { id: '21', text: 'Delaware Limited Partnership', },
        { id: '22', text: 'Delaware Limited Liability Company', },
        { id: '23', text: 'Delaware Statutory Trust', },
        { id: '24', text: 'Other', },
    ],
    nationalNomenclatureOfLegalFormItems: {
        '0': [ // Contractual Fund
            { id: '0', text: 'LU Fonds commun de placement (FCP)' },
            { id: '1', text: 'FR Fonds commun de placement (FCP)' },
            { id: '2', text: 'BE Fonds commun de placement (FCP)' },
            { id: '3', text: 'CH Vertraglicher Anlagefonds' },
            { id: '4', text: 'IE Common contractual fund (CCF)' },
            { id: '5', text: 'DE Sondervermögen im Eigentum der Kapitalverwaltungsgesellschaft oder im Miteigentum der Anleger (KAGB §92, Abs. 1)' },
            { id: '6', text: 'AT Kapitalanlagefonds verwaltet durch eine Kapitalanlagegesellschaft (Miteigentumsfonds)' },
            { id: '7', text: 'LI Investmentfonds (vertraglicher Anlagefonds)' },
            { id: '8', text: 'ES Fondo de inversión' },
            { id: '9', text: 'IT Fondo comune di investimento, Fondo speculativo' },
            { id: '10', text: 'MT Mutual fund' },
        ],
        '1': [ // Company with variable capital (SICAV)
            { id: '0', text: 'LU Société d\'investissement à capital variable' },
            { id: '1', text: 'FR Société d\'investissement à capital variable' },
            { id: '2', text: 'BE Société d\'investissement à capital variable' },
            { id: '3', text: 'GB Investment company with variable capital (ICVC)' },
            { id: '4', text: 'IE Investment company with variable capital (ICVC)' },
            { id: '5', text: 'CH Investmentgesellschaft mit variablem Kapital' },
            { id: '6', text: 'DE Investmentaktiengesellschaft (InvAG) mit veränderlichem Kapital (KAGB §108ff)' },
            { id: '7', text: 'DE Offene Investmentkommanditgesellschaft (InvKG) (KAGB §124ff)' },
            { id: '8', text: 'LI Investmentgesellschaft mit veränderlichem Kapital' },
            { id: '9', text: 'ES Sociedad de inversión de capital variable' },
            { id: '10', text: 'IT Società di investimento a capitale variabile' },
            { id: '11', text: 'MT Investment company with variable share capital' },
        ],
        '2': [ // Open-Ended Investment Company (OEIC)
            { id: '0', text: 'GB Open-ended investment company (OEIC)' },
            { id: '1', text: 'IE Open-ended investment company (OEIC)' },
            { id: '2', text: 'SG Open-ended investment company (OEIC)' },
            { id: '3', text: 'ID Open-ended investment company (OEIC)' },
        ],
        '3': [ // Company with fixed Capital (SICAF)
            { id: '0', text: 'LU Société d\'investissement à capital fixe' },
            { id: '1', text: 'CH Investmentgesellschaft mit festem Kapital' },
            { id: '2', text: 'FR Société d\'investissement à capital fixe' },
            { id: '3', text: 'BE Société d\'investissement à capital fixe' },
            { id: '4', text: 'DE Investmentaktiengesellschaft (InvAG) mit fixem Kapital' },
            { id: '5', text: 'MT Investment company with fixed share capital' },
        ],
        '4': unitTrustItems, // Unit Trust / Unit Investment Trust (UIT)
        '5': unitTrustItems,
        '6': [ // Limited Partnership (LP)
            { id: '0', text: 'CH Kommanditgesellschaft für kollektive Kapitalanlage (KGK)' },
            { id: '1', text: 'LI Kollektivtreuhänderschaft' },
            { id: '2', text: 'GB English limited partnership, Scottish limited partnership' },
            { id: '3', text: 'IE Investment limited partnership (ILP)' },
            { id: '4', text: 'VG Limited partnership' },
            { id: '5', text: 'GG Limited partnership' },
            { id: '6', text: 'JE Limited partnership' },
            { id: '7', text: 'SG Limited partnership' },
            { id: '8', text: 'US Limited partnership (limited partnership organised under US laws other than the State of Delaware)' },
            { id: '9', text: 'MT Investment partnership' },

        ],
        '7': [ // Limited Liability Partnership (LLP)
            { id: '0', text: 'SG Limited Liability Partnership' },
        ],
        '8': [ // Exempted Limited Partnership (ELP)
            { id: '0', text: 'KY Exempted Limited Partnership' },
            { id: '1', text: 'BM Exempted Limited Partnership' },
        ],
        '9': [ // Company treated as Limited Partnership
            { id: '0', text: 'Company treated as Limited Partnership' },
        ],
        '10': [ // Limited Company
            { id: '0', text: 'GB UK investment trust company (UK listed PLC\'s)' },
            { id: '1', text: 'IE Irish Collective Asset-management Vehicle (ICAV)' },
            { id: '2', text: 'US Corporation' },
            { id: '3', text: 'GG Company' },
            { id: '4', text: 'JE Company' },
        ],
        '11': [ // Limited Liability Company (LLC)
            { id: '0', text: 'HK Mutual fund' },
            { id: '1', text: 'US Limited liability company (organised under US laws other than the State of Delaware)' },
        ],
        '12': [ // Exempted Limited Liability Company
            { id: '0', text: 'Exempted Limited Liability Company' },
        ],
        '13': [ // Exempted Company
            { id: '0', text: 'KY Exempted company' },
            { id: '1', text: 'KY Exempted Segregated portfolio company (SPC)' },
            { id: '2', text: 'KY Exempted Limited duration company (LDC)' },
            { id: '3', text: 'BM BVI business company' },
            { id: '4', text: 'BM Segregated portfolio company (SPC)' },
            { id: '5', text: 'BM Mutual fund (defined in the Companies Act as "a company limited by shares … and stating in its memorandum that it is a mutual fund.")' },
        ],
        '14': [ // Corporation
            { id: '0', text: 'Corporation' },
        ],
        '15': [ // International Business Company (IBC)
            { id: '0', text: 'International Business Company (IBC)' },
        ],
        '16': [ // Cell Company (ICC / PCC)
            { id: '0', text: 'GG Protected cell company (PCC)' },
            { id: '1', text: 'JE Protected cell company (PCC)' },
            { id: '2', text: 'JE Incorporated cell company (ICC)' },
        ],
        '17': [ // Trust
            { id: '0', text: 'Trust' },
        ],
        '18': [ // US Mutual Fund
            { id: '0', text: 'US SEC registered Mutual fund' },
        ],
        '19': [ // US Face amount certificate company (FAC)
            { id: '0', text: 'US Face amount certificate company (FAC)' },
        ],
        '20': [ // US engaged Partnership
            { id: '0', text: 'US engaged Partnership' },
        ],
        '21': [ // Delaware Limited Partnership
            { id: '0', text: 'US Delaware limited partnership' },
        ],
        '22': [ // Delaware Limited Liability Company
            { id: '0', text: 'US Delaware limited liability company' },
        ],
        '23': [ // Delaware Statutory Trust
            { id: '0', text: 'US Delaware statutory trust' },
        ],
        '24': [ // Other
            { id: '0', text: 'Other' },
        ],
    },
    homeCountryLegalTypeItems: {
        'CH': [
            { id: '0', text: 'Securities fund' },
            { id: '1', text: 'Real estate fund' },
            { id: '2', text: 'Other funds for traditional investments' },
            { id: '3', text: 'Other funds for alternative investments' },
        ],
        'LU': [
            { id : '0', text: 'Partie I' },
            { id : '1', text: 'Partie II' },
            { id : '2', text: 'Specialized investment fund (SIF)' },
        ],
        'IE': [
            { id : '0', text: 'Retail fund' },
            { id : '1', text: 'Qualifying investor fund (QIF)' },
            { id : '2', text: 'Professional investor fund (PIF)' },
            { id : '3', text: 'Foreign fund' },
        ],
        'DE': [
            { id : '0', text: 'Inländischer OGAW (162ff KAGB)' },
            { id : '1', text: 'Offener inländischer Publikums-AIF (214ff KAGB)' },
            { id : '2', text: 'Geschlossener inländischer Publikums-AIF (261ff KAGB)' },
            { id : '3', text: 'Offener inländischer Spezial-AIF (278ff KAGB)' },
            { id : '4', text: 'Geschlossener inländischer Spezial-AIF (285ff KAGB)' },
        ],
        'SG': [
            { id : '0', text: 'Authorised CIS' },
            { id : '1', text: 'Restricted authorised CIS' },
        ],
    },
    fundCurrencyItems: [
        { text: 'ADB Unit of Account XUA', id: '0' },
        { text: 'Afghani AFN', id: '1' },
        { text: 'Algerian Dinar DZD', id: '2' },
        { text: 'Argentine Peso ARS', id: '3' },
        { text: 'Armenian Dram AMD', id: '4' },
        { text: 'Aruban Florin AWG', id: '5' },
        { text: 'Australian Dollar AUD', id: '6' },
        { text: 'Azerbaijan Manat AZN', id: '7' },
        { text: 'Bahamian Dollar BSD', id: '8' },
        { text: 'Bahraini Dinar BHD', id: '9' },
        { text: 'Baht THB', id: '10' },
        { text: 'Balboa PAB', id: '11' },
        { text: 'Barbados Dollar BBD', id: '12' },
        { text: 'Belarusian Ruble BYN', id: '13' },
        { text: 'Belize Dollar BZD', id: '14' },
        { text: 'Bermudian Dollar BMD', id: '15' },
        { text: 'Boliviano BOB', id: '16' },
        { text: 'Bolívar VEF', id: '17' },
        { text: 'Brazilian Real BRL', id: '18' },
        { text: 'Brunei Dollar BND', id: '19' },
        { text: 'Bulgarian Lev BGN', id: '20' },
        { text: 'Burundi Franc BIF', id: '21' },
        { text: 'CFA Franc BCEAO XOF', id: '22' },
        { text: 'CFA Franc BEAC XAF', id: '23' },
        { text: 'CFP Franc XPF', id: '24' },
        { text: 'Cabo Verde Escudo CVE', id: '25' },
        { text: 'Canadian Dollar CAD', id: '26' },
        { text: 'Cayman Islands Dollar KYD', id: '27' },
        { text: 'Chilean Peso CLP', id: '28' },
        { text: 'Colombian Peso COP', id: '29' },
        { text: 'Comorian Franc  KMF', id: '30' },
        { text: 'Congolese Franc CDF', id: '31' },
        { text: 'Convertible Mark BAM', id: '32' },
        { text: 'Cordoba Oro NIO', id: '33' },
        { text: 'Costa Rican Colon CRC', id: '34' },
        { text: 'Cuban Peso CUP', id: '35' },
        { text: 'Czech Koruna CZK', id: '36' },
        { text: 'Dalasi GMD', id: '37' },
        { text: 'Danish Krone DKK', id: '38' },
        { text: 'Denar MKD', id: '39' },
        { text: 'Djibouti Franc DJF', id: '40' },
        { text: 'Dobra STN', id: '41' },
        { text: 'Dominican Peso DOP', id: '42' },
        { text: 'Dong VND', id: '43' },
        { text: 'East Caribbean Dollar XCD', id: '44' },
        { text: 'Egyptian Pound EGP', id: '45' },
        { text: 'El Salvador Colon SVC', id: '46' },
        { text: 'Ethiopian Birr ETB', id: '47' },
        { text: 'Euro EUR', id: '48' },
        { text: 'Falkland Islands Pound FKP', id: '49' },
        { text: 'Fiji Dollar FJD', id: '50' },
        { text: 'Forint HUF', id: '51' },
        { text: 'Ghana Cedi GHS', id: '52' },
        { text: 'Gibraltar Pound GIP', id: '53' },
        { text: 'Gold XAU', id: '54' },
        { text: 'Gourde HTG', id: '55' },
        { text: 'Guarani PYG', id: '56' },
        { text: 'Guinean Franc GNF', id: '57' },
        { text: 'Guyana Dollar GYD', id: '58' },
        { text: 'Hong Kong Dollar HKD', id: '59' },
        { text: 'Hryvnia UAH', id: '60' },
        { text: 'Iceland Krona ISK', id: '61' },
        { text: 'Indian Rupee INR', id: '62' },
        { text: 'Iranian Rial IRR', id: '63' },
        { text: 'Iraqi Dinar IQD', id: '64' },
        { text: 'Jamaican Dollar JMD', id: '65' },
        { text: 'Jordanian Dinar JOD', id: '66' },
        { text: 'Kenyan Shilling KES', id: '67' },
        { text: 'Kina PGK', id: '68' },
        { text: 'Kuna HRK', id: '69' },
        { text: 'Kuwaiti Dinar KWD', id: '70' },
        { text: 'Kwanza AOA', id: '71' },
        { text: 'Kyat MMK', id: '72' },
        { text: 'Lao Kip LAK', id: '73' },
        { text: 'Lari GEL', id: '74' },
        { text: 'Lebanese Pound LBP', id: '75' },
        { text: 'Lek ALL', id: '76' },
        { text: 'Lempira HNL', id: '77' },
        { text: 'Leone SLL', id: '78' },
        { text: 'Liberian Dollar LRD', id: '79' },
        { text: 'Libyan Dinar LYD', id: '80' },
        { text: 'Lilangeni SZL', id: '81' },
        { text: 'Loti LSL', id: '82' },
        { text: 'Malagasy Ariary MGA', id: '83' },
        { text: 'Malawi Kwacha MWK', id: '84' },
        { text: 'Malaysian Ringgit MYR', id: '85' },
        { text: 'Mauritius Rupee MUR', id: '86' },
        { text: 'Mexican Peso MXN', id: '87' },
        { text: 'Mexican Unidad de Inversion (UDI) MXV', id: '88' },
        { text: 'Moldovan Leu MDL', id: '89' },
        { text: 'Moroccan Dirham MAD', id: '90' },
        { text: 'Mozambique Metical MZN', id: '91' },
        { text: 'Mvdol BOV', id: '92' },
        { text: 'Naira NGN', id: '93' },
        { text: 'Nakfa ERN', id: '94' },
        { text: 'Namibia Dollar NAD', id: '95' },
        { text: 'Nepalese Rupee NPR', id: '96' },
        { text: 'Netherlands Antillean Guilder ANG', id: '97' },
        { text: 'New Israeli Sheqel ILS', id: '98' },
        { text: 'New Taiwan Dollar TWD', id: '99' },
        { text: 'New Zealand Dollar NZD', id: '100' },
        { text: 'Ngultrum BTN', id: '101' },
        { text: 'North Korean Won KPW', id: '102' },
        { text: 'Norwegian Krone NOK', id: '103' },
        { text: 'Ouguiya MRU', id: '104' },
        { text: 'Pakistan Rupee PKR', id: '105' },
        { text: 'Palladium XPD', id: '106' },
        { text: 'Pataca MOP', id: '107' },
        { text: 'Pa’anga TOP', id: '108' },
        { text: 'Peso Convertible CUC', id: '109' },
        { text: 'Peso Uruguayo UYU', id: '110' },
        { text: 'Philippine Piso PHP', id: '111' },
        { text: 'Platinum XPT', id: '112' },
        { text: 'Pound Sterling GBP', id: '113' },
        { text: 'Pula BWP', id: '114' },
        { text: 'Qatari Rial QAR', id: '115' },
        { text: 'Quetzal GTQ', id: '116' },
        { text: 'Rand ZAR', id: '117' },
        { text: 'Rial Omani OMR', id: '118' },
        { text: 'Riel KHR', id: '119' },
        { text: 'Romanian Leu RON', id: '120' },
        { text: 'Rufiyaa MVR', id: '121' },
        { text: 'Rupiah IDR', id: '122' },
        { text: 'Russian Ruble RUB', id: '123' },
        { text: 'Rwanda Franc RWF', id: '124' },
        { text: 'SDR (Special Drawing Right) XDR', id: '125' },
        { text: 'Saint Helena Pound SHP', id: '126' },
        { text: 'Saudi Riyal SAR', id: '127' },
        { text: 'Serbian Dinar RSD', id: '128' },
        { text: 'Seychelles Rupee SCR', id: '129' },
        { text: 'Silver XAG', id: '130' },
        { text: 'Singapore Dollar SGD', id: '131' },
        { text: 'Sol PEN', id: '132' },
        { text: 'Solomon Islands Dollar SBD', id: '133' },
        { text: 'Som KGS', id: '134' },
        { text: 'Somali Shilling SOS', id: '135' },
        { text: 'Somoni TJS', id: '136' },
        { text: 'South Sudanese Pound SSP', id: '137' },
        { text: 'Sri Lanka Rupee LKR', id: '138' },
        { text: 'Sucre XSU', id: '139' },
        { text: 'Sudanese Pound SDG', id: '140' },
        { text: 'Surinam Dollar SRD', id: '141' },
        { text: 'Swedish Krona SEK', id: '142' },
        { text: 'Swiss Franc CHF', id: '143' },
        { text: 'Syrian Pound SYP', id: '144' },
        { text: 'Taka BDT', id: '145' },
        { text: 'Tala WST', id: '146' },
        { text: 'Tanzanian Shilling TZS', id: '147' },
        { text: 'Tenge KZT', id: '148' },
        { text: 'Trinidad and Tobago Dollar TTD', id: '149' },
        { text: 'Tugrik MNT', id: '150' },
        { text: 'Tunisian Dinar TND', id: '151' },
        { text: 'Turkish Lira TRY', id: '152' },
        { text: 'Turkmenistan New Manat TMT', id: '153' },
        { text: 'UAE Dirham AED', id: '154' },
        { text: 'US Dollar (Next day) USN', id: '155' },
        { text: 'US Dollar USD', id: '156' },
        { text: 'Uganda Shilling UGX', id: '157' },
        { text: 'Unidad de Fomento CLF', id: '158' },
        { text: 'Unidad de Valor Real COU', id: '159' },
        { text: 'Uruguay Peso en Unidades Indexadas (URUIURUI) UYI', id: '160' },
        { text: 'Uzbekistan Sum UZS', id: '161' },
        { text: 'Vatu VUV', id: '162' },
        { text: 'WIR Euro CHE', id: '163' },
        { text: 'WIR Franc CHW', id: '164' },
        { text: 'Won KRW', id: '165' },
        { text: 'Yemeni Rial YER', id: '166' },
        { text: 'Yen JPY', id: '167' },
        { text: 'Yuan Renminbi CNY', id: '168' },
        { text: 'Zambian Kwacha ZMW', id: '169' },
        { text: 'Zimbabwe Dollar ZWL', id: '170' },
        { text: 'Zloty PLN', id: '171' }
    ],
    portfolioCurrencyHedgeItems: [
        { id : '1', text: 'No Hedge' },
        { id : '2', text: 'Full Portfolio Hedge' },
        { id : '3', text: 'Currency overlay' },
        { id : '4', text: 'Partial Hedge' },
    ],
    fundAdministratorItems: [
        { id : '1', text: 'Fund Admin 1' },
        { id : '2', text: 'Fund Admin 2' },
        { id : '3', text: 'Fund Admin 3' },
    ],
    custodianBankItems: [
        { id : '1', text: 'Custodian Bank 1' },
        { id : '2', text: 'Custodian Bank 2' },
        { id : '3', text: 'Custodian Bank 3' },
    ],
    investmentManagerItems: [
        { id : '1', text: 'Investment Manager 1' },
        { id : '2', text: 'Investment Manager 2' },
        { id : '3', text: 'Investment Manager 3' },
    ],
    principalPromoterItems: [
        { id : '1', text: 'Principal Promoter 1' },
        { id : '2', text: 'Principal Promoter 2' },
        { id : '3', text: 'Principal Promoter 3' },
    ],
    payingAgentItems: [
        { id : '1', text: 'Paying Agent 1' },
        { id : '2', text: 'Paying Agent 2' },
        { id : '3', text: 'Paying Agent 3' },
    ],
    investmentAdvisorItems: [
        { id : '1', text: 'Investment Advisor 1' },
        { id : '2', text: 'Investment Advisor 2' },
        { id : '3', text: 'Investment Advisor 3' },
    ],
    auditorItems: [
        { id : '1', text: 'Auditor 1' },
        { id : '2', text: 'Auditor 2' },
        { id : '3', text: 'Auditor 3' },
    ],
    taxAuditorItems: [
        { id : '1', text: 'Tax Auditor 1' },
        { id : '2', text: 'Tax Auditor 2' },
        { id : '3', text: 'Tax Auditor 3' },
    ],
    legalAdvisorItems: [
        { id : '1', text: 'Legal Advisor 1' },
        { id : '2', text: 'Legal Advisor 2' },
        { id : '3', text: 'Legal Advisor 3' },
    ],
    capitalPreservationPeriodItems: [
        { id : '1', text: 'Daily' },
        { id : '2', text: 'Twice a week' },
        { id : '3', text: 'Weekly' },
        { id : '4', text: 'Twice a month' },
        { id : '5', text: 'Monthly' },
        { id : '6', text: 'Quarterly' },
        { id : '7', text: 'Twice a year' },
        { id : '8', text: 'Annually' },
    ],
    transferAgentItems: [
        { id : '1', text: 'transfer agent 1' },
        { id : '2', text: 'transfer agent 2' },
        { id : '3', text: 'transfer agent 3' },
    ],
    centralizingAgentItems: [
        { id : '1', text: 'centralizing agent 1' },
        { id : '2', text: 'centralizing agent 2' },
        { id : '3', text: 'centralizing agent 3' },
    ],
};

export default {
    enums,
    fundItems,
};
