import {name} from './__init__';
import {kAction} from '@setl/utils/common';

/* GENERAL */
export const SET_KYC_DETAILS_GENERAL = `${name}/SET_KYC_DETAILS_GENERAL`;

export const SET_KYC_DETAILS_GENERAL_REQUESTED = `${name}/SET_KYC_DETAILS_GENERAL_REQUESTED`;
export const setkycdetailsgeneralrequested = kAction(SET_KYC_DETAILS_GENERAL_REQUESTED);

export const CLEAR_KYC_DETAILS_GENERAL_REQUESTED = `${name}/CLEAR_KYC_DETAILS_GENERAL_REQUESTED`;
export const clearkycdetailsgeneralrequested = kAction(CLEAR_KYC_DETAILS_GENERAL_REQUESTED);

/* COMPANY */
export const SET_KYC_DETAILS_COMPANY = `${name}/SET_KYC_DETAILS_COMPANY`;

export const SET_KYC_DETAILS_COMPANY_REQUESTED = `${name}/SET_KYC_DETAILS_COMPANY_REQUESTED`;
export const setkycdetailscompanyrequested = kAction(SET_KYC_DETAILS_COMPANY_REQUESTED);

export const CLEAR_KYC_DETAILS_COMPANY_REQUESTED = `${name}/CLEAR_KYC_DETAILS_COMPANY_REQUESTED`;
export const clearkycdetailscompanyrequested = kAction(CLEAR_KYC_DETAILS_COMPANY_REQUESTED);

/* COMPANYBENEFICIARIES */
export const SET_KYC_DETAILS_COMPANYBENEFICIARIES = `${name}/SET_KYC_DETAILS_COMPANYBENEFICIARIES`;

export const SET_KYC_DETAILS_COMPANYBENEFICIARIES_REQUESTED = `${name}/SET_KYC_DETAILS_COMPANYBENEFICIARIES_REQUESTED`;
export const setkycdetailscompanybeneficiariesrequested = kAction(SET_KYC_DETAILS_COMPANYBENEFICIARIES_REQUESTED);

export const CLEAR_KYC_DETAILS_COMPANYBENEFICIARIES_REQUESTED = `${name}/CLEAR_KYC_DETAILS_COMPANYBENEFICIARIES_REQUESTED`;
export const clearkycdetailscompanybeneficiariesrequested = kAction(CLEAR_KYC_DETAILS_COMPANYBENEFICIARIES_REQUESTED);

/* BANKING */
export const SET_KYC_DETAILS_BANKING = `${name}/SET_KYC_DETAILS_BANKING`;

export const SET_KYC_DETAILS_BANKING_REQUESTED = `${name}/SET_KYC_DETAILS_BANKING_REQUESTED`;
export const setkycdetailsbankingrequested = kAction(SET_KYC_DETAILS_BANKING_REQUESTED);

export const CLEAR_KYC_DETAILS_BANKING_REQUESTED = `${name}/CLEAR_KYC_DETAILS_BANKING_REQUESTED`;
export const clearkycdetailsbankingrequested = kAction(CLEAR_KYC_DETAILS_BANKING_REQUESTED);

/* CLASSIFICATION */
export const SET_KYC_DETAILS_CLASSIFICATION = `${name}/SET_KYC_DETAILS_CLASSIFICATION`;

export const SET_KYC_DETAILS_CLASSIFICATION_REQUESTED = `${name}/SET_KYC_DETAILS_CLASSIFICATION_REQUESTED`;
export const setkycdetailsclassificationrequested = kAction(SET_KYC_DETAILS_CLASSIFICATION_REQUESTED);

export const CLEAR_KYC_DETAILS_CLASSIFICATION_REQUESTED = `${name}/CLEAR_KYC_DETAILS_CLASSIFICATION_REQUESTED`;
export const clearkycdetailsclassificationrequested = kAction(CLEAR_KYC_DETAILS_CLASSIFICATION_REQUESTED);

/* RISKNATURE */
export const SET_KYC_DETAILS_RISKNATURE = `${name}/SET_KYC_DETAILS_RISKNATURE`;

export const SET_KYC_DETAILS_RISKNATURE_REQUESTED = `${name}/SET_KYC_DETAILS_RISKNATURE_REQUESTED`;
export const setkycdetailsrisknaturerequested = kAction(SET_KYC_DETAILS_RISKNATURE_REQUESTED);

export const CLEAR_KYC_DETAILS_RISKNATURE_REQUESTED = `${name}/CLEAR_KYC_DETAILS_RISKNATURE_REQUESTED`;
export const clearkycdetailsrisknaturerequested = kAction(CLEAR_KYC_DETAILS_RISKNATURE_REQUESTED);

/* RISKOBJECTIVES + RISKCONSTRAINTS */
export const SET_KYC_DETAILS_RISKOBJECTIVES = `${name}/SET_KYC_DETAILS_RISKOBJECTIVES`;

export const SET_KYC_DETAILS_RISKOBJECTIVES_REQUESTED = `${name}/SET_KYC_DETAILS_RISKOBJECTIVES_REQUESTED`;
export const setkycdetailsriskobjectivesrequested = kAction(SET_KYC_DETAILS_RISKOBJECTIVES_REQUESTED);

export const CLEAR_KYC_DETAILS_RISKOBJECTIVES_REQUESTED = `${name}/CLEAR_KYC_DETAILS_RISKOBJECTIVES_REQUESTED`;
export const clearkycdetailsriskobjectivesrequested = kAction(CLEAR_KYC_DETAILS_RISKOBJECTIVES_REQUESTED);

/* DOCUMENTS */
export const SET_KYC_DETAILS_DOCUMENTS = `${name}/SET_KYC_DETAILS_DOCUMENTS`;

export const SET_KYC_DETAILS_DOCUMENTS_REQUESTED = `${name}/SET_KYC_DETAILS_DOCUMENTS_REQUESTED`;
export const setkycdetailsdocumentsrequested = kAction(SET_KYC_DETAILS_DOCUMENTS_REQUESTED);

export const CLEAR_KYC_DETAILS_DOCUMENTS_REQUESTED = `${name}/CLEAR_KYC_DETAILS_DOCUMENTS_REQUESTED`;
export const clearkycdetailsdocumentsrequested = kAction(CLEAR_KYC_DETAILS_DOCUMENTS_REQUESTED);

export const CLEAR_KYC_DETAILS_ALL = `${name}/CLEAR_KYC_DETAILS_ALL`;
export const clearkycdetailsall = kAction(CLEAR_KYC_DETAILS_ALL);

export const SET_KYC_DETAILS_VALIDATION = `${name}/SET_KYC_DETAILS_VALIDATION`;

export const SET_KYC_DETAILS_VALIDATION_REQUESTED = `${name}/SET_KYC_DETAILS_VALIDATION_REQUESTED`;
export const setkycdetailsvalidationrequested = kAction(SET_KYC_DETAILS_VALIDATION_REQUESTED);

export const CLEAR_KYC_DETAILS_VALIDATION_REQUESTED = `${name}/CLEAR_KYC_DETAILS_VALIDATION_REQUESTED`;
export const clearkycdetailsvalidationrequested = kAction(CLEAR_KYC_DETAILS_VALIDATION_REQUESTED);