const unitTrustItems = [ // Unit Trust / Unit Investment Trust (UIT)
    { id: 'GB', text: 'GB Authorised unit trust (AUT)' },
    { id: 'US', text: 'US For US UIT refer to "US Mutual Fund"' },
    { id: 'KY', text: 'KY (Exempted) Unit trust' },
    { id: 'IE', text: 'IE Unit trust' },
    { id: 'VG', text: 'VG Unit trust' },
    { id: 'VM', text: 'VM Unit trust' },
    { id: 'GG', text: 'GG Unit trust' },
    { id: 'JE', text: 'JE Unit trust' },
    { id: 'HK', text: 'HK Unit trust' },
    { id: 'SG', text: 'SG Unit trust' },
    { id: 'MT', text: 'MT Unit trust' },
];

export default {
    fundDomicileItems: [
        {id: 'AF', text: 'Afghanistan'},
        {id: 'AL', text: 'Albania'},
        {id: 'DZ', text: 'Algeria'},
        {id: 'AS', text: 'American Samoa'},
        {id: 'AD', text: 'Andorra'},
        {id: 'AO', text: 'Angola'},
        {id: 'AI', text: 'Anguilla'},
        {id: 'AQ', text: 'Antarctica'},
        {id: 'AG', text: 'Antigua And Barbuda'},
        {id: 'AR', text: 'Argentina'},
        {id: 'AM', text: 'Armenia'},
        {id: 'AW', text: 'Aruba'},
        {id: 'AU', text: 'Australia'},
        {id: 'AT', text: 'Austria'},
        {id: 'AZ', text: 'Azerbaijan'},
        {id: 'BS', text: 'Bahamas'},
        {id: 'BH', text: 'Bahrain'},
        {id: 'BD', text: 'Bangladesh'},
        {id: 'BB', text: 'Barbados'},
        {id: 'BY', text: 'Belarus'},
        {id: 'BE', text: 'Belgium'},
        {id: 'BZ', text: 'Belize'},
        {id: 'BJ', text: 'Benin'},
        {id: 'BM', text: 'Bermuda'},
        {id: 'BT', text: 'Bhutan'},
        {id: 'BO', text: 'Bolivia'},
        {id: 'BA', text: 'Bosnia And Herzegovina'},
        {id: 'BW', text: 'Botswana'},
        {id: 'BV', text: 'Bouvet Island'},
        {id: 'BR', text: 'Brazil'},
        {id: 'IO', text: 'British Indian Ocean Territory'},
        {id: 'BN', text: 'Brunei Darussalam'},
        {id: 'BG', text: 'Bulgaria'},
        {id: 'BF', text: 'Burkina Faso'},
        {id: 'BI', text: 'Burundi'},
        {id: 'KH', text: 'Cambodia'},
        {id: 'CM', text: 'Cameroon'},
        {id: 'CA', text: 'Canada'},
        {id: 'CV', text: 'Cape Verde'},
        {id: 'KY', text: 'Cayman Islands'},
        {id: 'CF', text: 'Central African Republic'},
        {id: 'TD', text: 'Chad'},
        {id: 'CL', text: 'Chile'},
        {id: 'CN', text: 'China'},
        {id: 'CX', text: 'Christmas Island'},
        {id: 'CC', text: 'Cocos (keeling) Islands'},
        {id: 'CO', text: 'Colombia'},
        {id: 'KM', text: 'Comoros'},
        {id: 'CG', text: 'Congo'},
        {id: 'CD', text: 'Congo, The Democratic Republic Of The'},
        {id: 'CK', text: 'Cook Islands'},
        {id: 'CR', text: 'Costa Rica'},
        {id: 'CI', text: 'Cote D\'ivoire'},
        {id: 'HR', text: 'Croatia'},
        {id: 'CU', text: 'Cuba'},
        {id: 'CY', text: 'Cyprus'},
        {id: 'CZ', text: 'Czech Republic'},
        {id: 'DK', text: 'Denmark'},
        {id: 'DJ', text: 'Djibouti'},
        {id: 'DM', text: 'Dominica'},
        {id: 'DO', text: 'Dominican Republic'},
        {id: 'TP', text: 'East Timor'},
        {id: 'EC', text: 'Ecuador'},
        {id: 'EG', text: 'Egypt'},
        {id: 'SV', text: 'El Salvador'},
        {id: 'GQ', text: 'Equatorial Guinea'},
        {id: 'ER', text: 'Eritrea'},
        {id: 'EE', text: 'Estonia'},
        {id: 'ET', text: 'Ethiopia'},
        {id: 'FK', text: 'Falkland Islands (malvinas)'},
        {id: 'FO', text: 'Faroe Islands'},
        {id: 'FJ', text: 'Fiji'},
        {id: 'FI', text: 'Finland'},
        {id: 'FR', text: 'France'},
        {id: 'GF', text: 'French Guiana'},
        {id: 'PF', text: 'French Polynesia'},
        {id: 'TF', text: 'French Southern Territories'},
        {id: 'GA', text: 'Gabon'},
        {id: 'GM', text: 'Gambia'},
        {id: 'GE', text: 'Georgia'},
        {id: 'DE', text: 'Germany'},
        {id: 'GH', text: 'Ghana'},
        {id: 'GI', text: 'Gibraltar'},
        {id: 'GR', text: 'Greece'},
        {id: 'GL', text: 'Greenland'},
        {id: 'GD', text: 'Grenada'},
        {id: 'GP', text: 'Guadeloupe'},
        {id: 'GU', text: 'Guam'},
        {id: 'GT', text: 'Guatemala'},
        {id: 'GN', text: 'Guinea'},
        {id: 'GW', text: 'Guinea-bissau'},
        {id: 'GY', text: 'Guyana'},
        {id: 'HT', text: 'Haiti'},
        {id: 'HM', text: 'Heard Island And Mcdonald Islands'},
        {id: 'VA', text: 'Holy See (vatican City State)'},
        {id: 'HN', text: 'Honduras'},
        {id: 'HK', text: 'Hong Kong'},
        {id: 'HU', text: 'Hungary'},
        {id: 'IS', text: 'Iceland'},
        {id: 'IN', text: 'India'},
        {id: 'ID', text: 'Indonesia'},
        {id: 'IR', text: 'Iran, Islamic Republic Of'},
        {id: 'IQ', text: 'Iraq'},
        {id: 'IE', text: 'Ireland'},
        {id: 'IL', text: 'Israel'},
        {id: 'IT', text: 'Italy'},
        {id: 'JM', text: 'Jamaica'},
        {id: 'JP', text: 'Japan'},
        {id: 'JO', text: 'Jordan'},
        {id: 'KZ', text: 'Kazakstan'},
        {id: 'KE', text: 'Kenya'},
        {id: 'KI', text: 'Kiribati'},
        {id: 'KP', text: 'Korea, Democratic People\'s Republic Of'},
        {id: 'KR', text: 'Korea, Republic Of'},
        {id: 'KV', text: 'Kosovo'},
        {id: 'KW', text: 'Kuwait'},
        {id: 'KG', text: 'Kyrgyzstan'},
        {id: 'LA', text: 'Lao People\'s Democratic Republic'},
        {id: 'LV', text: 'Latvia'},
        {id: 'LB', text: 'Lebanon'},
        {id: 'LS', text: 'Lesotho'},
        {id: 'LR', text: 'Liberia'},
        {id: 'LY', text: 'Libyan Arab Jamahiriya'},
        {id: 'LI', text: 'Liechtenstein'},
        {id: 'LT', text: 'Lithuania'},
        {id: 'LU', text: 'Luxembourg'},
        {id: 'MO', text: 'Macau'},
        {id: 'MK', text: 'Macedonia, The Former Yugoslav Republic Of'},
        {id: 'MG', text: 'Madagascar'},
        {id: 'MW', text: 'Malawi'},
        {id: 'MY', text: 'Malaysia'},
        {id: 'MV', text: 'Maldives'},
        {id: 'ML', text: 'Mali'},
        {id: 'MT', text: 'Malta'},
        {id: 'MH', text: 'Marshall Islands'},
        {id: 'MQ', text: 'Martinique'},
        {id: 'MR', text: 'Mauritania'},
        {id: 'MU', text: 'Mauritius'},
        {id: 'YT', text: 'Mayotte'},
        {id: 'MX', text: 'Mexico'},
        {id: 'FM', text: 'Micronesia, Federated States Of'},
        {id: 'MD', text: 'Moldova, Republic Of'},
        {id: 'MC', text: 'Monaco'},
        {id: 'MN', text: 'Mongolia'},
        {id: 'MS', text: 'Montserrat'},
        {id: 'ME', text: 'Montenegro'},
        {id: 'MA', text: 'Morocco'},
        {id: 'MZ', text: 'Mozambique'},
        {id: 'MM', text: 'Myanmar'},
        {id: 'NA', text: 'Namibia'},
        {id: 'NR', text: 'Nauru'},
        {id: 'NP', text: 'Nepal'},
        {id: 'NL', text: 'Netherlands'},
        {id: 'AN', text: 'Netherlands Antilles'},
        {id: 'NC', text: 'New Caledonia'},
        {id: 'NZ', text: 'New Zealand'},
        {id: 'NI', text: 'Nicaragua'},
        {id: 'NE', text: 'Niger'},
        {id: 'NG', text: 'Nigeria'},
        {id: 'NU', text: 'Niue'},
        {id: 'NF', text: 'Norfolk Island'},
        {id: 'MP', text: 'Northern Mariana Islands'},
        {id: 'NO', text: 'Norway'},
        {id: 'OM', text: 'Oman'},
        {id: 'PK', text: 'Pakistan'},
        {id: 'PW', text: 'Palau'},
        {id: 'PS', text: 'Palestinian Territory, Occupied'},
        {id: 'PA', text: 'Panama'},
        {id: 'PG', text: 'Papua New Guinea'},
        {id: 'PY', text: 'Paraguay'},
        {id: 'PE', text: 'Peru'},
        {id: 'PH', text: 'Philippines'},
        {id: 'PN', text: 'Pitcairn'},
        {id: 'PL', text: 'Poland'},
        {id: 'PT', text: 'Portugal'},
        {id: 'PR', text: 'Puerto Rico'},
        {id: 'QA', text: 'Qatar'},
        {id: 'RE', text: 'Reunion'},
        {id: 'RO', text: 'Romania'},
        {id: 'RU', text: 'Russian Federation'},
        {id: 'RW', text: 'Rwanda'},
        {id: 'SH', text: 'Saint Helena'},
        {id: 'KN', text: 'Saint Kitts And Nevis'},
        {id: 'LC', text: 'Saint Lucia'},
        {id: 'PM', text: 'Saint Pierre And Miquelon'},
        {id: 'VC', text: 'Saint Vincent And The Grenadines'},
        {id: 'WS', text: 'Samoa'},
        {id: 'SM', text: 'San Marino'},
        {id: 'ST', text: 'Sao Tome And Principe'},
        {id: 'SA', text: 'Saudi Arabia'},
        {id: 'SN', text: 'Senegal'},
        {id: 'RS', text: 'Serbia'},
        {id: 'SC', text: 'Seychelles'},
        {id: 'SL', text: 'Sierra Leone'},
        {id: 'SG', text: 'Singapore'},
        {id: 'SK', text: 'Slovakia'},
        {id: 'SI', text: 'Slovenia'},
        {id: 'SB', text: 'Solomon Islands'},
        {id: 'SO', text: 'Somalia'},
        {id: 'ZA', text: 'South Africa'},
        {id: 'GS', text: 'South Georgia And The South Sandwich Islands'},
        {id: 'ES', text: 'Spain'},
        {id: 'LK', text: 'Sri Lanka'},
        {id: 'SD', text: 'Sudan'},
        {id: 'SR', text: 'Suriname'},
        {id: 'SJ', text: 'Svalbard And Jan Mayen'},
        {id: 'SZ', text: 'Swaziland'},
        {id: 'SE', text: 'Sweden'},
        {id: 'CH', text: 'Switzerland'},
        {id: 'SY', text: 'Syrian Arab Republic'},
        {id: 'TW', text: 'Taiwan, Province Of China'},
        {id: 'TJ', text: 'Tajikistan'},
        {id: 'TZ', text: 'Tanzania, United Republic Of'},
        {id: 'TH', text: 'Thailand'},
        {id: 'TG', text: 'Togo'},
        {id: 'TK', text: 'Tokelau'},
        {id: 'TO', text: 'Tonga'},
        {id: 'TT', text: 'Trinidad And Tobago'},
        {id: 'TN', text: 'Tunisia'},
        {id: 'TR', text: 'Turkey'},
        {id: 'TM', text: 'Turkmenistan'},
        {id: 'TC', text: 'Turks And Caicos Islands'},
        {id: 'TV', text: 'Tuvalu'},
        {id: 'UG', text: 'Uganda'},
        {id: 'UA', text: 'Ukraine'},
        {id: 'AE', text: 'United Arab Emirates'},
        {id: 'GB', text: 'United Kingdom'},
        {id: 'US', text: 'United States'},
        {id: 'UM', text: 'United States Minor Outlying Islands'},
        {id: 'UY', text: 'Uruguay'},
        {id: 'UZ', text: 'Uzbekistan'},
        {id: 'VU', text: 'Vanuatu'},
        {id: 'VE', text: 'Venezuela'},
        {id: 'VN', text: 'Viet Nam'},
        {id: 'VG', text: 'Virgin Islands, British'},
        {id: 'VI', text: 'Virgin Islands, U.s.'},
        {id: 'WF', text: 'Wallis And Futuna'},
        {id: 'EH', text: 'Western Sahara'},
        {id: 'YE', text: 'Yemen'},
        {id: 'ZM', text: 'Zambia'},
        {id: 'ZW', text: 'Zimbabwe'},
    ],
    umbrellaItems: [
        {
            id: 0,
            text: 'none'
        },
        {
            id: 1,
            text: 'umbrella 1'
        },
        {
            id: 2,
            text: 'umbrella 2'
        },
        {
            id: 3,
            text: 'umbrella 3'
        },
        {
            id: 4,
            text: 'umbrella 4'
        },
    ],
    isEuDirectiveRelevantItems: [
        {
            id: 'UCITS',
            text: 'UCITS',
        },
        {
            id: 'AIF',
            text: 'AIF',
        },
        {
            id: 'Other',
            text: 'Other',
        },
    ],
    UCITSVersionItems: [
        {
            id: 3,
            text: 'UCITS III',
        },
        {
            id: 4,
            text: 'UCITS IV',
        },
        {
            id: 5,
            text: 'UCITS V',
        },
        {
            id: 6,
            text: 'UCITS VI',
        },
    ],
    fundLegalFormItems: [
        { id: '0', text: 'Contractual Fund', },
        { id: '1', text: 'Company With Variable Capital (SICAV)', },
        { id: '2', text: 'Open-ended Investment Company (OEIC)', },
        { id: '3', text: 'Company With Fixed Capital (SICAF)', },
        { id: '4', text: 'Unit Trust', },
        { id: '5', text: 'Unit Investment Trust (UIT)', },
        { id: '6', text: 'Limited Partnership (LP)', },
        { id: '7', text: 'Limited Liability Partnership (LLP)', },
        { id: '8', text: 'Exempted Limited Partnership (ELP)', },
        { id: '9', text: 'Company treated as Limited Partnership', },
        { id: '10', text: 'Limited Company', },
        { id: '11', text: 'Limited Liability Company (LLC)', },
        { id: '12', text: 'Exempted Limited Liability Company', },
        { id: '13', text: 'Exempted Company', },
        { id: '14', text: 'Corporation', },
        { id: '15', text: 'International Business Company (IBC)', },
        { id: '16', text: 'Cell Company (ICC / PCC)', },
        { id: '17', text: 'Trust', },
        { id: '18', text: 'US Mutual Fund', },
        { id: '19', text: 'US Face Amount Certificate Company (FAC)', },
        { id: '20', text: 'US engaged Partnership', },
        { id: '21', text: 'Delaware Limited Partnership', },
        { id: '22', text: 'Delaware Limited Liability Company', },
        { id: '23', text: 'Delaware Statutory Trust', },
        { id: '24', text: 'Other', },
    ],
    nationalNomenclatureOfLegalFormItems: {
        '0': [ // Contractual Fund
            { id: 'LU', text: 'LU Fonds commun de placement (FCP)' },
            { id: 'FR', text: 'FR Fonds commun de placement (FCP)' },
            { id: 'BE', text: 'BE Fonds commun de placement (FCP)' },
            { id: 'CH', text: 'CH Vertraglicher Anlagefonds' },
            { id: 'IE', text: 'IE Common contractual fund (CCF)' },
            { id: 'DE', text: 'DE Sondervermögen im Eigentum der Kapitalverwaltungsgesellschaft oder im Miteigentum der Anleger (KAGB §92, Abs. 1)' },
            { id: 'AT', text: 'AT Kapitalanlagefonds verwaltet durch eine Kapitalanlagegesellschaft (Miteigentumsfonds)' },
            { id: 'LI', text: 'LI Investmentfonds (vertraglicher Anlagefonds)' },
            { id: 'ES', text: 'ES Fondo de inversión' },
            { id: 'IT', text: 'IT Fondo comune di investimento, Fondo speculativo' },
            { id: 'MT', text: 'MT Mutual fund' },
        ],
        '1': [ // Company with variable capital (SICAV)
            { id: 'LU', text: 'LU Société d\'investissement à capital variable' },
            { id: 'FR', text: 'FR Société d\'investissement à capital variable' },
            { id: 'BE', text: 'BE Société d\'investissement à capital variable' },
            { id: 'GB', text: 'GB Investment company with variable capital (ICVC)' },
            { id: 'IE', text: 'IE Investment company with variable capital (ICVC)' },
            { id: 'CH', text: 'CH Investmentgesellschaft mit variablem Kapital' },
            { id: 'DE', text: 'DE Investmentaktiengesellschaft (InvAG) mit veränderlichem Kapital (KAGB §108ff)' },
            { id: 'DE', text: 'DE Offene Investmentkommanditgesellschaft (InvKG) (KAGB §124ff)' },
            { id: 'LI', text: 'LI Investmentgesellschaft mit veränderlichem Kapital' },
            { id: 'ES', text: 'ES Sociedad de inversión de capital variable' },
            { id: 'IT', text: 'IT Società di investimento a capitale variabile' },
            { id: 'MT', text: 'MT Investment company with variable share capital' },
        ],
        '2': [ // Open-Ended Investment Company (OEIC)
            { id: 'GB', text: 'GB Open-ended investment company (OEIC)' },
            { id: 'IE', text: 'IE Open-ended investment company (OEIC)' },
            { id: 'SG', text: 'SG Open-ended investment company (OEIC)' },
            { id: 'ID', text: 'ID Open-ended investment company (OEIC)' },
        ],
        '3': [ // Company with fixed Capital (SICAF)
            { id: 'LU', text: 'LU Société d\'investissement à capital fixe' },
            { id: 'CH', text: 'CH Investmentgesellschaft mit festem Kapital' },
            { id: 'FR', text: 'FR Société d\'investissement à capital fixe' },
            { id: 'BE', text: 'BE Société d\'investissement à capital fixe' },
            { id: 'DE', text: 'DE Investmentaktiengesellschaft (InvAG) mit fixem Kapital' },
            { id: 'MT', text: 'MT Investment company with fixed share capital' },
        ],
        '4': unitTrustItems, // Unit Trust / Unit Investment Trust (UIT)
        '5': unitTrustItems,
        '6': [ // Limited Partnership (LP)
            { id: 'CH', text: 'CH Kommanditgesellschaft für kollektive Kapitalanlage (KGK)' },
            { id: 'LI', text: 'LI Kollektivtreuhänderschaft' },
            { id: 'GB', text: 'GB English limited partnership, Scottish limited partnership' },
            { id: 'IE', text: 'IE Investment limited partnership (ILP)' },
            { id: 'VG', text: 'VG Limited partnership' },
            { id: 'GG', text: 'GG Limited partnership' },
            { id: 'JE', text: 'JE Limited partnership' },
            { id: 'SG', text: 'SG Limited partnership' },
            { id: 'US', text: 'US Limited partnership (limited partnership organised under US laws other than the State of Delaware)' },
            { id: 'MT', text: 'MT Investment partnership' },

        ],
        '7': [ // Limited Liability Partnership (LLP)
            { id: 'SG', text: 'SG Limited Liability Partnership' },
        ],
        '8': [ // Exempted Limited Partnership (ELP)
            { id: 'KY', text: 'KY Exempted Limited Partnership' },
            { id: 'BM', text: 'BM Exempted Limited Partnership' },
        ],
        '9': [ // Company treated as Limited Partnership
            { id: '0', text: 'Company treated as Limited Partnership' },
        ],
        '10': [ // Limited Company
            { id: 'GB', text: 'GB UK investment trust company (UK listed PLC\'s)' },
            { id: 'IE', text: 'IE Irish Collective Asset-management Vehicle (ICAV)' },
            { id: 'US', text: 'US Corporation' },
            { id: 'GG', text: 'GG Company' },
            { id: 'JE', text: 'JE Company' },
        ],
        '11': [ // Limited Liability Company (LLC)
            { id: 'HK', text: 'HK Mutual fund' },
            { id: 'US', text: 'US Limited liability company (organised under US laws other than the State of Delaware)' },
        ],
        '12': [ // Exempted Limited Liability Company
            { id: '0', text: 'Exempted Limited Liability Company' },
        ],
        '13': [ // Exempted Company
            { id: 'KY', text: 'KY Exempted company' },
            { id: 'KY', text: 'KY Exempted Segregated portfolio company (SPC)' },
            { id: 'KY', text: 'KY Exempted Limited duration company (LDC)' },
            { id: 'BM', text: 'BM BVI business company' },
            { id: 'BM', text: 'BM Segregated portfolio company (SPC)' },
            { id: 'BM', text: 'BM Mutual fund (defined in the Companies Act as "a company limited by shares … and stating in its memorandum that it is a mutual fund.")' },
        ],
        '14': [ // Corporation
            { id: '0', text: 'Corporation' },
        ],
        '15': [ // International Business Company (IBC)
            { id: '0', text: 'International Business Company (IBC)' },
        ],
        '16': [ // Cell Company (ICC / PCC)
            { id: 'GG', text: 'GG Protected cell company (PCC)' },
            { id: 'JE', text: 'JE Protected cell company (PCC)' },
            { id: 'JE', text: 'JE Incorporated cell company (ICC)' },
        ],
        '17': [ // Trust
            { id: '0', text: 'Trust' },
        ],
        '18': [ // US Mutual Fund
            { id: 'US', text: 'US SEC registered Mutual fund' },
        ],
        '19': [ // US Face amount certificate company (FAC)
            { id: 'US', text: 'US Face amount certificate company (FAC)' },
        ],
        '20': [ // US engaged Partnership
            { id: '0', text: 'US engaged Partnership' },
        ],
        '21': [ // Delaware Limited Partnership
            { id: 'US', text: 'US Delaware limited partnership' },
        ],
        '22': [ // Delaware Limited Liability Company
            { id: 'US', text: 'US Delaware limited liability company' },
        ],
        '23': [ // Delaware Statutory Trust
            { id: 'US', text: 'US Delaware statutory trust' },
        ],
        '24': [ // Other
            { id: '0', text: 'Other' },
        ],
    },
    homeCountryLegalTypeItems: {
        'CH': [
            { id: '0', text: 'Securities fund' },
            { id: '1', text: 'Real estate fund' },
            { id: '2', text: 'Other funds for traditional investments' },
            { id: '3', text: 'Other funds for alternative investments' },
        ],
        'LU': [
            { id : '0', text: 'Partie I' },
            { id : '1', text: 'Partie II' },
            { id : '2', text: 'Specialized investment fund (SIF)' },
        ],
        'IE': [
            { id : '0', text: 'Retail fund' },
            { id : '1', text: 'Qualifying investor fund (QIF)' },
            { id : '2', text: 'Professional investor fund (PIF)' },
            { id : '3', text: 'Foreign fund' },
        ],
        'DE': [
            { id : '0', text: 'Inländischer OGAW (162ff KAGB)' },
            { id : '1', text: 'Offener inländischer Publikums-AIF (214ff KAGB)' },
            { id : '2', text: 'Geschlossener inländischer Publikums-AIF (261ff KAGB)' },
            { id : '3', text: 'Offener inländischer Spezial-AIF (278ff KAGB)' },
            { id : '4', text: 'Geschlossener inländischer Spezial-AIF (285ff KAGB)' },
        ],
        'SG': [
            { id : '0', text: 'Authorised CIS' },
            { id : '1', text: 'Restricted authorised CIS' },
        ],
    },
    fundCurrencyItems: [
        { text: 'ADB Unit of Account XUA', id: 'XUA' },
        { text: 'Afghani AFN', id: 'AFN' },
        { text: 'Algerian Dinar DZD', id: 'DZD' },
        { text: 'Argentine Peso ARS', id: 'ARS' },
        { text: 'Armenian Dram AMD', id: 'AMD' },
        { text: 'Aruban Florin AWG', id: 'AWG' },
        { text: 'Australian Dollar AUD', id: 'AUD' },
        { text: 'Azerbaijan Manat AZN', id: 'AZN' },
        { text: 'Bahamian Dollar BSD', id: 'BSD' },
        { text: 'Bahraini Dinar BHD', id: 'BHD' },
        { text: 'Baht THB', id: 'THB' },
        { text: 'Balboa PAB', id: 'PAB' },
        { text: 'Barbados Dollar BBD', id: 'BBD' },
        { text: 'Belarusian Ruble BYN', id: 'BYN' },
        { text: 'Belize Dollar BZD', id: 'BZD' },
        { text: 'Bermudian Dollar BMD', id: 'BMD' },
        { text: 'Boliviano BOB', id: 'BOB' },
        { text: 'Bolívar VEF', id: 'VEF' },
        { text: 'Brazilian Real BRL', id: 'BRL' },
        { text: 'Brunei Dollar BND', id: 'BND' },
        { text: 'Bulgarian Lev BGN', id: 'BGN' },
        { text: 'Burundi Franc BIF', id: 'BIF' },
        { text: 'CFA Franc BCEAO XOF', id: 'XOF' },
        { text: 'CFA Franc BEAC XAF', id: 'XAF' },
        { text: 'CFP Franc XPF', id: 'XPF' },
        { text: 'Cabo Verde Escudo CVE', id: 'CVE' },
        { text: 'Canadian Dollar CAD', id: 'CAD' },
        { text: 'Cayman Islands Dollar KYD', id: 'KYD' },
        { text: 'Chilean Peso CLP', id: 'CLP' },
        { text: 'Colombian Peso COP', id: 'COP' },
        { text: 'Comorian Franc  KMF', id: 'KMF' },
        { text: 'Congolese Franc CDF', id: 'CDF' },
        { text: 'Convertible Mark BAM', id: 'BAM' },
        { text: 'Cordoba Oro NIO', id: 'NIO' },
        { text: 'Costa Rican Colon CRC', id: 'CRC' },
        { text: 'Cuban Peso CUP', id: 'CUP' },
        { text: 'Czech Koruna CZK', id: 'CZK' },
        { text: 'Dalasi GMD', id: 'GMD' },
        { text: 'Danish Krone DKK', id: 'DKK' },
        { text: 'Denar MKD', id: 'MKD' },
        { text: 'Djibouti Franc DJF', id: 'DJF' },
        { text: 'Dobra STN', id: 'STN' },
        { text: 'Dominican Peso DOP', id: 'DOP' },
        { text: 'Dong VND', id: 'VND' },
        { text: 'East Caribbean Dollar XCD', id: 'XCD' },
        { text: 'Egyptian Pound EGP', id: 'EGP' },
        { text: 'El Salvador Colon SVC', id: 'SVC' },
        { text: 'Ethiopian Birr ETB', id: 'ETB' },
        { text: 'Euro EUR', id: 'EUR' },
        { text: 'Falkland Islands Pound FKP', id: 'FKP' },
        { text: 'Fiji Dollar FJD', id: 'FJD' },
        { text: 'Forint HUF', id: 'HUF' },
        { text: 'Ghana Cedi GHS', id: 'GHS' },
        { text: 'Gibraltar Pound GIP', id: 'GIP' },
        { text: 'Gold XAU', id: 'XAU' },
        { text: 'Gourde HTG', id: 'HTG' },
        { text: 'Guarani PYG', id: 'PYG' },
        { text: 'Guinean Franc GNF', id: 'GNF' },
        { text: 'Guyana Dollar GYD', id: 'GYD' },
        { text: 'Hong Kong Dollar HKD', id: 'HKD' },
        { text: 'Hryvnia UAH', id: 'UAH' },
        { text: 'Iceland Krona ISK', id: 'ISK' },
        { text: 'Indian Rupee INR', id: 'INR' },
        { text: 'Iranian Rial IRR', id: 'IRR' },
        { text: 'Iraqi Dinar IQD', id: 'IQD' },
        { text: 'Jamaican Dollar JMD', id: 'JMD' },
        { text: 'Jordanian Dinar JOD', id: 'JOD' },
        { text: 'Kenyan Shilling KES', id: 'KES' },
        { text: 'Kina PGK', id: 'PGK' },
        { text: 'Kuna HRK', id: 'HRK' },
        { text: 'Kuwaiti Dinar KWD', id: 'KWD' },
        { text: 'Kwanza AOA', id: 'AOA' },
        { text: 'Kyat MMK', id: 'MMK' },
        { text: 'Lao Kip LAK', id: 'LAK' },
        { text: 'Lari GEL', id: 'GEL' },
        { text: 'Lebanese Pound LBP', id: 'LBP' },
        { text: 'Lek ALL', id: 'ALL' },
        { text: 'Lempira HNL', id: 'HNL' },
        { text: 'Leone SLL', id: 'SLL' },
        { text: 'Liberian Dollar LRD', id: 'LRD' },
        { text: 'Libyan Dinar LYD', id: 'LYD' },
        { text: 'Lilangeni SZL', id: 'SZL' },
        { text: 'Loti LSL', id: 'LSL' },
        { text: 'Malagasy Ariary MGA', id: 'MGA' },
        { text: 'Malawi Kwacha MWK', id: 'MWK' },
        { text: 'Malaysian Ringgit MYR', id: 'MYR' },
        { text: 'Mauritius Rupee MUR', id: 'MUR' },
        { text: 'Mexican Peso MXN', id: 'MXN' },
        { text: 'Mexican Unidad de Inversion (UDI) MXV', id: 'MXV' },
        { text: 'Moldovan Leu MDL', id: 'MDL' },
        { text: 'Moroccan Dirham MAD', id: 'MAD' },
        { text: 'Mozambique Metical MZN', id: 'MZN' },
        { text: 'Mvdol BOV', id: 'BOV' },
        { text: 'Naira NGN', id: 'NGN' },
        { text: 'Nakfa ERN', id: 'ERN' },
        { text: 'Namibia Dollar NAD', id: 'NAD' },
        { text: 'Nepalese Rupee NPR', id: 'NPR' },
        { text: 'Netherlands Antillean Guilder ANG', id: 'ANG' },
        { text: 'New Israeli Sheqel ILS', id: 'ILS' },
        { text: 'New Taiwan Dollar TWD', id: 'TWD' },
        { text: 'New Zealand Dollar NZD', id: 'NZD' },
        { text: 'Ngultrum BTN', id: 'BTN' },
        { text: 'North Korean Won KPW', id: 'KPW' },
        { text: 'Norwegian Krone NOK', id: 'NOK' },
        { text: 'Ouguiya MRU', id: 'MRU' },
        { text: 'Pakistan Rupee PKR', id: 'PKR' },
        { text: 'Palladium XPD', id: 'XPD' },
        { text: 'Pataca MOP', id: 'MOP' },
        { text: 'Pa’anga TOP', id: 'TOP' },
        { text: 'Peso Convertible CUC', id: 'CUC' },
        { text: 'Peso Uruguayo UYU', id: 'UYU' },
        { text: 'Philippine Piso PHP', id: 'PHP' },
        { text: 'Platinum XPT', id: 'XPT' },
        { text: 'Pound Sterling GBP', id: 'GBP' },
        { text: 'Pula BWP', id: 'BWP' },
        { text: 'Qatari Rial QAR', id: 'QAR' },
        { text: 'Quetzal GTQ', id: 'GTQ' },
        { text: 'Rand ZAR', id: 'ZAR' },
        { text: 'Rial Omani OMR', id: 'OMR' },
        { text: 'Riel KHR', id: 'KHR' },
        { text: 'Romanian Leu RON', id: 'RON' },
        { text: 'Rufiyaa MVR', id: 'MVR' },
        { text: 'Rupiah IDR', id: 'IDR' },
        { text: 'Russian Ruble RUB', id: 'RUB' },
        { text: 'Rwanda Franc RWF', id: 'RWF' },
        { text: 'SDR (Special Drawing Right) XDR', id: 'XDR' },
        { text: 'Saint Helena Pound SHP', id: 'SHP' },
        { text: 'Saudi Riyal SAR', id: 'SAR' },
        { text: 'Serbian Dinar RSD', id: 'RSD' },
        { text: 'Seychelles Rupee SCR', id: 'SCR' },
        { text: 'Silver XAG', id: 'XAG' },
        { text: 'Singapore Dollar SGD', id: 'SGD' },
        { text: 'Sol PEN', id: 'PEN' },
        { text: 'Solomon Islands Dollar SBD', id: 'SBD' },
        { text: 'Som KGS', id: 'KGS' },
        { text: 'Somali Shilling SOS', id: 'SOS' },
        { text: 'Somoni TJS', id: 'TJS' },
        { text: 'South Sudanese Pound SSP', id: 'SSP' },
        { text: 'Sri Lanka Rupee LKR', id: 'LKR' },
        { text: 'Sucre XSU', id: 'XSU' },
        { text: 'Sudanese Pound SDG', id: 'SDG' },
        { text: 'Surinam Dollar SRD', id: 'SRD' },
        { text: 'Swedish Krona SEK', id: 'SEK' },
        { text: 'Swiss Franc CHF', id: 'CHF' },
        { text: 'Syrian Pound SYP', id: 'SYP' },
        { text: 'Taka BDT', id: 'BDT' },
        { text: 'Tala WST', id: 'WST' },
        { text: 'Tanzanian Shilling TZS', id: 'TZS' },
        { text: 'Tenge KZT', id: 'KZT' },
        { text: 'Trinidad and Tobago Dollar TTD', id: 'TTD' },
        { text: 'Tugrik MNT', id: 'MNT' },
        { text: 'Tunisian Dinar TND', id: 'TND' },
        { text: 'Turkish Lira TRY', id: 'TRY' },
        { text: 'Turkmenistan New Manat TMT', id: 'TMT' },
        { text: 'UAE Dirham AED', id: 'AED' },
        { text: 'US Dollar (Next day) USN', id: 'USN' },
        { text: 'US Dollar USD', id: 'USD' },
        { text: 'Uganda Shilling UGX', id: 'UGX' },
        { text: 'Unidad de Fomento CLF', id: 'CLF' },
        { text: 'Unidad de Valor Real COU', id: 'COU' },
        { text: 'Uruguay Peso en Unidades Indexadas (URUIURUI) UYI', id: 'UYI' },
        { text: 'Uzbekistan Sum UZS', id: 'UZS' },
        { text: 'Vatu VUV', id: 'VUV' },
        { text: 'WIR Euro CHE', id: 'CHE' },
        { text: 'WIR Franc CHW', id: 'CHW' },
        { text: 'Won KRW', id: 'KRW' },
        { text: 'Yemeni Rial YER', id: 'YER' },
        { text: 'Yen JPY', id: 'JPY' },
        { text: 'Yuan Renminbi CNY', id: 'CNY' },
        { text: 'Zambian Kwacha ZMW', id: 'ZMW' },
        { text: 'Zimbabwe Dollar ZWL', id: 'ZWL' },
        { text: 'Zloty PLN', id: 'PLN' },
    ],
    portfolioCurrencyHedgeItems: [
        { id : '1', text: 'No Hedge' },
        { id : '2', text: 'Full Portfolio Hedge' },
        { id : '3', text: 'Currency overlay' },
        { id : '4', text: 'Partial Hedge' },
    ],
    investmentAdvisorItems: [
        { id : '1', text: 'Investment Advisor 1' },
        { id : '2', text: 'Investment Advisor 2' },
        { id : '3', text: 'Investment Advisor 3' },
    ],
    auditorItems: [
        { id : '1', text: 'Auditor 1' },
        { id : '2', text: 'Auditor 2' },
        { id : '3', text: 'Auditor 3' },
    ],
    taxAuditorItems: [
        { id : '1', text: 'Tax Auditor 1' },
        { id : '2', text: 'Tax Auditor 2' },
        { id : '3', text: 'Tax Auditor 3' },
    ],
    legalAdvisorItems: [
        { id : '1', text: 'Legal Advisor 1' },
        { id : '2', text: 'Legal Advisor 2' },
        { id : '3', text: 'Legal Advisor 3' },
    ],
};
