import {name} from './__init__';
import {kAction} from '@setl/utils/common';

// getKycGeneral
// getKycCompany
// getKycBanking
// getKycClassification
// getKycRisknature
// getKycRiskobjective // (objectives + constraints)
// getKycDocument

// getKycCompanybeneficiaries // modal


/* GENERAL */
export const SET_KYC_MYREQ_DETAILS_GENERAL = `${name}/SET_KYC_MYREQ_DETAILS_GENERAL`;

export const SET_KYC_MYREQ_DETAILS_GENERAL_REQUESTED = `${name}/SET_KYC_MYREQ_DETAILS_GENERAL_REQUESTED`;
export const setkycmyreqdetailsgeneralrequested = kAction(SET_KYC_MYREQ_DETAILS_GENERAL_REQUESTED);

export const CLEAR_KYC_MYREQ_DETAILS_GENERAL_REQUESTED = `${name}/CLEAR_KYC_MYREQ_DETAILS_GENERAL_REQUESTED`;
export const clearkycmyreqdetailsgeneralrequested = kAction(CLEAR_KYC_MYREQ_DETAILS_GENERAL_REQUESTED);

/* COMPANY */
export const SET_KYC_MYREQ_DETAILS_COMPANY = `${name}/SET_KYC_MYREQ_DETAILS_COMPANY`;

export const SET_KYC_MYREQ_DETAILS_COMPANY_REQUESTED = `${name}/SET_KYC_MYREQ_DETAILS_COMPANY_REQUESTED`;
export const setkycmyreqdetailscompanyrequested = kAction(SET_KYC_MYREQ_DETAILS_COMPANY_REQUESTED);

export const CLEAR_KYC_MYREQ_DETAILS_COMPANY_REQUESTED = `${name}/CLEAR_KYC_MYREQ_DETAILS_COMPANY_REQUESTED`;
export const clearkycmyreqdetailscompanyrequested = kAction(CLEAR_KYC_MYREQ_DETAILS_COMPANY_REQUESTED);

/* COMPANYBENEFICIARIES */
export const SET_KYC_MYREQ_DETAILS_COMPANYBENEFICIARIES = `${name}/SET_KYC_MYREQ_DETAILS_COMPANYBENEFICIARIES`;

export const SET_KYC_MYREQ_DETAILS_COMPANYBENEFICIARIES_REQUESTED = `${name}/SET_KYC_MYREQ_DETAILS_COMPANYBENEFICIARIES_REQUESTED`;
export const setkycmyreqdetailscompanybeneficiariesrequested = kAction(SET_KYC_MYREQ_DETAILS_COMPANYBENEFICIARIES_REQUESTED);

export const CLEAR_KYC_MYREQ_DETAILS_COMPANYBENEFICIARIES_REQUESTED = `${name}/CLEAR_KYC_MYREQ_DETAILS_COMPANYBENEFICIARIES_REQUESTED`;
export const clearkycmyreqdetailscompanybeneficiariesrequested = kAction(CLEAR_KYC_MYREQ_DETAILS_COMPANYBENEFICIARIES_REQUESTED);

/* BANKING */
export const SET_KYC_MYREQ_DETAILS_BANKING = `${name}/SET_KYC_MYREQ_DETAILS_BANKING`;

export const SET_KYC_MYREQ_DETAILS_BANKING_REQUESTED = `${name}/SET_KYC_MYREQ_DETAILS_BANKING_REQUESTED`;
export const setkycmyreqdetailsbankingrequested = kAction(SET_KYC_MYREQ_DETAILS_BANKING_REQUESTED);

export const CLEAR_KYC_MYREQ_DETAILS_BANKING_REQUESTED = `${name}/CLEAR_KYC_MYREQ_DETAILS_BANKING_REQUESTED`;
export const clearkycmyreqdetailsbankingrequested = kAction(CLEAR_KYC_MYREQ_DETAILS_BANKING_REQUESTED);

/* CLASSIFICATION */
export const SET_KYC_MYREQ_DETAILS_CLASSIFICATION = `${name}/SET_KYC_MYREQ_DETAILS_CLASSIFICATION`;

export const SET_KYC_MYREQ_DETAILS_CLASSIFICATION_REQUESTED = `${name}/SET_KYC_MYREQ_DETAILS_CLASSIFICATION_REQUESTED`;
export const setkycmyreqdetailsclassificationrequested = kAction(SET_KYC_MYREQ_DETAILS_CLASSIFICATION_REQUESTED);

export const CLEAR_KYC_MYREQ_DETAILS_CLASSIFICATION_REQUESTED = `${name}/CLEAR_KYC_MYREQ_DETAILS_CLASSIFICATION_REQUESTED`;
export const clearkycmyreqdetailsclassificationrequested = kAction(CLEAR_KYC_MYREQ_DETAILS_CLASSIFICATION_REQUESTED);

/* RISKNATURE */
export const SET_KYC_MYREQ_DETAILS_RISKNATURE = `${name}/SET_KYC_MYREQ_DETAILS_RISKNATURE`;

export const SET_KYC_MYREQ_DETAILS_RISKNATURE_REQUESTED = `${name}/SET_KYC_MYREQ_DETAILS_RISKNATURE_REQUESTED`;
export const setkycmyreqdetailsrisknaturerequested = kAction(SET_KYC_MYREQ_DETAILS_RISKNATURE_REQUESTED);

export const CLEAR_KYC_MYREQ_DETAILS_RISKNATURE_REQUESTED = `${name}/CLEAR_KYC_MYREQ_DETAILS_RISKNATURE_REQUESTED`;
export const clearkycmyreqdetailsrisknaturerequested = kAction(CLEAR_KYC_MYREQ_DETAILS_RISKNATURE_REQUESTED);

/* RISKOBJECTIVES + RISKCONSTRAINTS */
export const SET_KYC_MYREQ_DETAILS_RISKOBJECTIVES = `${name}/SET_KYC_MYREQ_DETAILS_RISKOBJECTIVES`;

export const SET_KYC_MYREQ_DETAILS_RISKOBJECTIVES_REQUESTED = `${name}/SET_KYC_MYREQ_DETAILS_RISKOBJECTIVES_REQUESTED`;
export const setkycmyreqdetailsriskobjectivesrequested = kAction(SET_KYC_MYREQ_DETAILS_RISKOBJECTIVES_REQUESTED);

export const CLEAR_KYC_MYREQ_DETAILS_RISKOBJECTIVES_REQUESTED = `${name}/CLEAR_KYC_MYREQ_DETAILS_RISKOBJECTIVES_REQUESTED`;
export const clearkycmyreqdetailsriskobjectivesrequested = kAction(CLEAR_KYC_MYREQ_DETAILS_RISKOBJECTIVES_REQUESTED);

/* DOCUMENTS */
export const SET_KYC_MYREQ_DETAILS_DOCUMENTS = `${name}/SET_KYC_MYREQ_DETAILS_DOCUMENTS`;

export const SET_KYC_MYREQ_DETAILS_DOCUMENTS_REQUESTED = `${name}/SET_KYC_MYREQ_DETAILS_DOCUMENTS_REQUESTED`;
export const setkycmyreqdetailsdocumentsrequested = kAction(SET_KYC_MYREQ_DETAILS_DOCUMENTS_REQUESTED);

export const CLEAR_KYC_MYREQ_DETAILS_DOCUMENTS_REQUESTED = `${name}/CLEAR_KYC_MYREQ_DETAILS_DOCUMENTS_REQUESTED`;
export const clearkycmyreqdetailsdocumentsrequested = kAction(CLEAR_KYC_MYREQ_DETAILS_DOCUMENTS_REQUESTED);

